import type { Project } from "@/lib/types";

export const projects: Project[] = [
  {
    id: 1,
    slug: "esi-flow",
    name: "ESI Flow",
    role: "Team Lead — 5-person team",
    pinned: true,
    summary: "A production, multi-role SaaS platform serving students, technicians, and admins at ESI.",
    bullets: [
      "Led a 5-member team through system design, database architecture, and end-to-end implementation using Agile sprints.",
      "Contributed ~80% of the Express/TypeScript/PostgreSQL codebase, including JWT-secured RBAC across 3 user types and the full Prisma schema.",
      "Validated cross-layer reliability across 15+ frontend pages and the REST API with function and integration tests; deployed to Vercel and Render.",
    ],
    stack: ["Next.js", "TypeScript", "Express.js", "Prisma", "PostgreSQL", "JWT"],
    media: [
      { type: "image", src: "/media/esi-flow/dashboard.png", alt: "ESI Flow dashboard" },
      { type: "image", src: "/media/esi-flow/tickets.png", alt: "ESI Flow ticketing view" },
    ],
    links: {
      live: { available: true, url: "https://esi-flow.vercel.app" },
      github: { available: true, url: "https://github.com/Erraid7" },
      demoVideo: { available: false, reason: "No walkthrough video recorded yet — the live site above covers this." },
    },
    docsMarkdown: `## ESI Flow\n\nA multi-role SaaS system built for ESI: students file requests, technicians resolve them, admins oversee the whole flow.\n\n(Replace with full case-study writing.)`,
  },
  {
    id: 2,
    slug: "khatma",
    name: "Khatma",
    role: "Solo Full-Stack Developer",
    pinned: true,
    summary: "A full-stack Quran memorization platform, sole-authored across web and mobile.",
    bullets: [
      "Covered 3 user roles (Hafiz, Teacher, Admin) across a Next.js web app and a cross-platform Flutter app.",
      "Designed the full Prisma/PostgreSQL schema and built a secure REST API with JWT authentication, independently.",
      "Implemented all backend logic in TypeScript/Express, from data model to deployed service.",
    ],
    stack: ["Next.js", "TypeScript", "Flutter", "Node.js", "Express", "Prisma", "PostgreSQL", "JWT"],
    media: [
      { type: "image", src: "/media/khatma/web-home.png", alt: "Khatma web home screen" },
      { type: "video", src: "/media/khatma/mobile-demo.mp4", poster: "/media/khatma/mobile-poster.png", alt: "Khatma Flutter app demo" },
    ],
    links: {
      live: { available: false, reason: "Not deployed publicly yet — currently used within a closed pilot group." },
      github: { available: true, url: "https://github.com/Erraid7" },
      demoVideo: { available: true },
    },
    docsMarkdown: `## Khatma\n\n(Replace with full case-study writing.)`,
  },
  {
    id: 3,
    slug: "refactoring-swarm",
    name: "Refactoring Swarm",
    role: "Designer & Builder",
    pinned: true,
    summary: "An autonomous 4-agent pipeline — Auditor, Fixer, Tester, Documenter — that reviews, refactors, tests, and documents Python code.",
    bullets: [
      "Eliminated manual code-review overhead by chaining agents that analyze quality, propose refactors, generate tests, and update docs.",
      "Applied swarm-intelligence principles to coordinate LLM-powered agents with clearly separated responsibilities.",
      "Structured inter-agent communication so each agent's output becomes verified input for the next.",
    ],
    stack: ["Python", "LLM APIs", "Multi-agent systems"],
    media: [
      { type: "image", src: "/media/refactoring-swarm/pipeline-diagram.png", alt: "Agent pipeline diagram" },
    ],
    links: {
      live: { available: false, reason: "This is a CLI/pipeline tool, not a hosted app — no live URL applies." },
      github: { available: true, url: "https://github.com/Erraid7" },
      demoVideo: { available: false, reason: "Recording planned — check back soon." },
    },
    docsMarkdown: `## Refactoring Swarm\n\n(Replace with full case-study writing.)`,
  },
  {
    id: 4,
    slug: "esi-run",
    name: "ESI Run",
    role: "Developer",
    pinned: true,
    summary: "A desktop public-transportation management system: accounts, pass management, complaint handling, and validation workflows.",
    bullets: [
      "Implemented full business logic in Java/JavaFX with CSV-based persistence.",
      "Wrote unit and integration tests across the user, pass, and validation subsystems.",
    ],
    stack: ["Java", "JavaFX"],
    media: [
      { type: "image", src: "/media/esi-run/main-window.png", alt: "ESI Run main window" },
    ],
    links: {
      live: { available: false, reason: "Desktop application — not applicable, there's no hosted version." },
      github: { available: true, url: "https://github.com/Erraid7" },
      demoVideo: { available: false, reason: "Recording planned — check back soon." },
    },
    docsMarkdown: `## ESI Run\n\n(Replace with full case-study writing.)`,
  },
  {
    id: 5,
    slug: "cse-website",
    name: "CSE Club Website",
    role: "Contributor",
    pinned: true,
    summary: "The public site for Club Scientifique de l'ESI — responsive components and an infinite-scroll, direction-reactive sponsor slider.",
    bullets: [
      "Built responsive frontend components used across the club's public site.",
      "Implemented an infinite-scroll sponsor slider with direction-reactive animation.",
    ],
    stack: ["Next.js", "TypeScript", "Tailwind CSS"],
    media: [
      { type: "image", src: "/media/cse-website/homepage.png", alt: "CSE club website homepage" },
    ],
    links: {
      live: { available: true, url: "https://cse-esi.com" },
      github: { available: true, url: "https://github.com/Erraid7" },
      demoVideo: { available: false, reason: "No walkthrough video recorded yet." },
    },
    docsMarkdown: `## CSE Club Website\n\n(Replace with full case-study writing.)`,
  },
  {
    id: 6,
    slug: "confidential-client-project",
    name: "Confidential Client Project",
    role: "Freelance Full-Stack Developer",
    pinned: false,
    summary: "A commercial project built for a private client. Most details are under NDA.",
    bullets: [
      "PLACEHOLDER: describe the problem and your contribution in general terms that don't violate the NDA.",
    ],
    stack: ["Next.js", "PostgreSQL"],
    media: [],
    links: {
      live: { available: false, reason: "Confidential — the client has not authorized a public link." },
      github: { available: false, reason: "Private repository under client NDA." },
      demoVideo: { available: false, reason: "Not permitted to share due to client confidentiality." },
    },
    docsMarkdown: `## Confidential Client Project\n\nDetails limited by NDA.`,
  },
  {
    id: 7,
    slug: "untitled-experiment",
    name: "Untitled AI Experiment",
    role: "Solo",
    pinned: false,
    summary: "An early-stage personal experiment, not yet ready to be a headline project.",
    bullets: ["PLACEHOLDER: replace with a real minor/side project."],
    stack: ["Python"],
    media: [],
    links: {
      live: { available: false, reason: "Early prototype — not deployed." },
      github: { available: true, url: "https://github.com/Erraid7" },
      demoVideo: { available: false, reason: "No demo recorded yet." },
    },
    docsMarkdown: `## Untitled AI Experiment\n\n(Replace with real content or delete this entry.)`,
  },
];
